language: cpp

cache:
  - apt

services:
  - docker

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --remote
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update  -qq; fi
  - docker build -t ubuntu18.04dev .

script:
  - docker run -v $PWD/:/mnt/AppFramework ubuntu18.04dev:latest /bin/bash -c  "mkdir /tmp/build/ && cd /tmp/build/ ; cmake -DENABLE_TESTS=ON /mnt/AppFramework/code/ && make -j3 && ./Core/sample/sample_sinewaverunner ./plugin/ ;"

branches:
  only:
  - master
  - development

sudo: enabled

notifications:
    email:
      on_success: always # default: change
      on_failure: always # default: always
