
unset(JSONCPP_WITH_TESTS)
set(JSONCPP_WITH_TESTS OFF CACHE BOOL "")
unset(JSONCPP_WITH_POST_BUILD_UNITTEST)
set(JSONCPP_WITH_POST_BUILD_UNITTEST OFF CACHE BOOL "")
add_subdirectory(${CMAKE_SOURCE_DIR}/submodule/jsoncpp)
set(JSONCPP_INC_DIR ${CMAKE_SOURCE_DIR}/submodule/jsoncpp/include)
